version: "3"

services:
  proxy:
    build: .
    ports:
      - "8080:8090"
    environment:
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=3000
      - DASHBOARD_HOST=dashboard
      - DASHBOARD_PORT=8080
      - BACKEND_HOST=api
      - BACKEND_PORT=8001
      - PORT=8090
  frontend:
    image: denser-web/landing

  dashboard:
    image: denser-web/dashboard

  api:
    image: denser-web/api
    environment:
      - NODE_ENV=development
      - PORT=8001
