version: "3"

services:
  proxy:
    build: .
    volumes:
      # - ./Caddyfile:/app/Caddyfile
      - ./denser.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=3000
      - DASHBOARD_HOST=dashboard
      - DASHBOARD_PORT=8080
      - BACKEND_HOST=api
      - BACKEND_PORT=8001

  frontend:
    image: denser-web/landing

  dashboard:
    image: denser-web/dashboard

  backend:
    image: denser-web/api
    environment:
      - NODE_ENV=development
      - PORT=8001
