version: "3"

services:
  proxy:
    build: .
    volumes:
      - ./Caddyfile:/app/Caddyfile
    ports:
      - "8080:8090"
    environment:
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=3000
      - DASHBOARD_HOST=dashboard
      - DASHBOARD_PORT=8080
      - BACKEND_HOST=backend
      - BACKEND_PORT=8001
      - PORT=8090

  nginx:
    image: nginx:alpine
    volumes:
      - ./denser.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8088:80"

  frontend:
    image: denser-web/landing

  dashboard:
    image: denser-web/dashboard

  backend:
    image: denser-web/api
    environment:
      - NODE_ENV=development
      - PORT=8001
